### ISSUE TITLE
Plays not working

### ISSUE THREAD

**Issue by JimHewitt** [pratikthanki/FourthDown#31]
Tried https://localhost:44365/api/game/plays?GameId=2020_17_DAL_NYG and it returned:

{"title":"There are errors with your request.","status":400,"errors":{"requiredField":["Week or team must be provided."],"query":["If gameId is used then Week, Season and Team do not need to be provided"]}}

**Comment by pratikthanki** [comment]
Thanks for raising this, found the issue and fixed it in - https://github.com/pratikthanki/FourthDown/pull/32

You can pull the latest image with the fix - [pratikthanki9/fourthdown-api:latest](https://hub.docker.com/repository/docker/pratikthanki9/fourthdown-api)

Your request here now running - https://fourthdown.azurewebsites.net/api/game/plays?GameId=2020_17_DAL_NYG

**Comment by pratikthanki** [comment]
@JimHewitt is this all good your end too?

**Comment by JimHewitt** [comment]
@pratikthanki Yes.  Thanks.
